version: "3.3"
services:
  update-screenshots:
    build: .
    volumes:
      - "./config:/root/config:ro"
      - "./tests/screenshots:/root/tests/screenshots:rw"
      - "./output:/root/output:rw"
    entrypoint: ["/bin/sh", "-c", "/usr/bin/xvfb-run -a $$@", ""]
    command: yarn codeceptjs:updateScreenshots
