image: node:16.13.1
stages:
  - build
  - test
  - release

default:
  cache:
    paths:
      - .yarn
  before_script:
    # install dependencies for canvas
    - apt-get update
    - apt-get install -y build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
    - yarn install --cache-folder .yarn

extension:
  stage: build
  script:
    - yarn build
  artifacts:
    paths:
      - public/build
  only:
    - branches
  except:
    - schedules

e2e-image:
  image: docker:latest
  stage: build
  variables:
    MASTER_IMAGE_CACHE: $CI_REGISTRY_IMAGE:branch-master
    BRANCH_IMAGE_CACHE: $CI_REGISTRY_IMAGE:branch-$CI_COMMIT_REF_NAME
    NEW_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  services:
    - docker:dind
  cache: {}
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker pull $MASTER_IMAGE_CACHE || true
    - docker pull $BRANCH_IMAGE_CACHE || true
    - >
      docker build
      --cache-from $MASTER_IMAGE_CACHE
      --cache-from $BRANCH_IMAGE_CACHE
      --tag $NEW_IMAGE
      .
    - docker push $NEW_IMAGE
    - docker tag $NEW_IMAGE $BRANCH_IMAGE_CACHE
    - docker push $BRANCH_IMAGE_CACHE
  only:
    - branches
  except:
    - schedules

lint:
  stage: test
  script:
    - yarn lint
  only:
    - branches
  except:
    - schedules

jest:
  stage: test
  script:
    - yarn test
  only:
    - branches
  except:
    - schedules

.e2e-base:
  variables:
    GIT_STRATEGY: none
  image: "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA"
  stage: test
  cache: {}
  before_script: []
  script:
    - cd /root
    - xvfb-run -a yarn codeceptjs:ci
  after_script:
    - cp -r /root/output .
    - mkdir -p tests/screenshots
    - cp -r /root/tests/screenshots ./tests
    - echo "🔗 -> $CI_PROJECT_URL/-/jobs/$CI_JOB_ID/artifacts/file/output/html/mochawesome.html"
  artifacts:
    paths:
      - output
      - tests/screenshots
    reports:
      junit: output/result.xml
    when: always
  only:
    - branches

e2e-gitlab:
  extends: .e2e-base
  variables:
    E2E_PRODUCT: "gitlab"

e2e-github:
  extends: .e2e-base
  variables:
    E2E_PRODUCT: "github"

publish:
  stage: build
  script:
    - yarn build
    - yarn web-ext-submit
    - yarn webstore upload --source "web-ext-artifacts/conventional_comments-${CI_COMMIT_TAG:1}.zip" --auto-publish
  artifacts:
    paths:
      - "web-ext-artifacts/*.zip"
  only:
    - tags
  except:
    - schedules

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  before_script: []
  script:
    - >
      release-cli create --name "Release $CI_COMMIT_TAG"
      --tag-name $CI_COMMIT_TAG
      --assets-link "{\"name\":\"conventional_comments-$CI_COMMIT_TAG.zip\",\"url\":\"https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/jobs/artifacts/$CI_COMMIT_TAG/raw/web-ext-artifacts/conventional_comments-${CI_COMMIT_TAG:1}.zip?job=publish\"}"
  only:
    - tags
  except:
    - schedules
