name: Release
on:
  push:
    tags:
      - "v*"
jobs:
  build:
    name: Build
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.13.1
          cache: yarn
          cache-dependency-path: ./yarn.lock

      - name: Install deps
        run: yarn install --frozen-lockfile

      - name: Build extension
        run: yarn build

      - name: Save extension
        id: cache-extention
        uses: actions/cache@v4
        with:
          path: public/web-ext-artifacts
          key: extension-${{ github.run_id }}

  publish-firefox:
    name: Publish Firefox
    timeout-minutes: 10
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.13.1
          cache: yarn
          cache-dependency-path: ./yarn.lock

      - name: Install deps
        run: yarn install --frozen-lockfile

      - name: Restore extension
        id: cache-extention
        uses: actions/cache@v4
        with:
          path: public/build
          key: extension-${{ github.run_id }}

      - name: Publish
        run: yarn web-ext-submit

  publish-chrome:
    name: Publish Chrome
    timeout-minutes: 10
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.13.1
          cache: yarn
          cache-dependency-path: ./yarn.lock

      - name: Install deps
        run: yarn install --frozen-lockfile

      - name: Restore extension
        id: cache-extention
        uses: actions/cache@v4
        with:
          path: public/build
          key: extension-${{ github.run_id }}

      - name: Publish
        run: yarn chrome-webstore-upload upload --source "web-ext-artifacts/conventional_comments-${GITHUB_REF:1}.zip" --auto-publish

  create-release:
    name: Create Release
    timeout-minutes: 10
    runs-on: ubuntu-latest
    needs: [publish-firefox, publish-chrome]
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Restore extension
        id: cache-extention
        uses: actions/cache@v4
        with:
          path: public/build
          key: extension-${{ github.run_id }}

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "web-ext-artifacts/*.zip"
